CREATE TABLE Users (
	id VARCHAR(36),
    email VARCHAR(255) NOT NULL UNIQUE,
    passwords TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (Id)
);